"""Compile and run model-written trading strategies, safely enough.

Threat model: code generated by our own fine-tuned model — buggy, possibly
degenerate (infinite loops, exceptions, contract violations), but not an
adversarial human. In-process Python sandboxing is never bulletproof; the
defenses here are a builtins whitelist (no imports, no I/O, no eval), a
wall-clock alarm, and strict output validation. Do not use this to run
untrusted third-party code.
"""

from __future__ import annotations

import builtins as _builtins
import math
import re
import signal
from contextlib import contextmanager

import numpy as np
import pandas as pd


class StrategyError(Exception):
    """The generated code violated the contract (no code, crash, bad output)."""


class StrategyTimeout(StrategyError):
    """The generated code exceeded its wall-clock budget."""


# --- code extraction ----------------------------------------------------------

_CODE_BLOCK_RE = re.compile(r"```(?:python)?\s*\n(.*?)```", re.DOTALL)


def extract_code(text: str) -> str | None:
    """Pull the strategy source out of a model completion.

    Prefers the last fenced code block (the prompt asks for exactly one);
    falls back to everything from 'def allocate' onward for fence-less output.
    """
    blocks = _CODE_BLOCK_RE.findall(text)
    for block in reversed(blocks):
        if "def allocate" in block:
            return block
    idx = text.find("def allocate")
    if idx != -1:
        return text[idx:]
    return None


# --- restricted execution ------------------------------------------------------

_ALLOWED_BUILTINS = [
    "abs", "all", "any", "bool", "dict", "divmod", "enumerate", "filter",
    "float", "frozenset", "int", "isinstance", "len", "list", "map", "max",
    "min", "pow", "range", "reversed", "round", "set", "slice", "sorted",
    "str", "sum", "tuple", "zip",
    "ValueError", "KeyError", "IndexError", "TypeError", "ZeroDivisionError",
    "ArithmeticError", "StopIteration", "Exception",
]

SAFE_BUILTINS = {name: getattr(_builtins, name) for name in _ALLOWED_BUILTINS}
SAFE_BUILTINS["print"] = lambda *a, **k: None  # silence, don't crash


class _SafeModule:
    """Shallow module proxy that blocks I/O entry points.

    Closes the lookahead side-door: without this, generated code could call
    pd.read_parquet(...) on the price snapshot sitting on disk and read the
    future. Shallow only — instance methods (df.to_csv) are not intercepted;
    acceptable under our threat model (writing leaks nothing about the future).
    """

    _BLOCKED = ("read_", "load", "save", "fromfile", "loadtxt", "genfromtxt",
                "savetxt", "memmap", "to_pickle", "io", "eval", "lib")

    def __init__(self, module):
        object.__setattr__(self, "_module", module)

    def __getattr__(self, name):
        if name.startswith("_") or any(
            name == b or name.startswith(b) for b in self._BLOCKED
        ):
            raise StrategyError(f"{self._module.__name__}.{name} is not available")
        return getattr(self._module, name)

    def __setattr__(self, name, value):
        raise StrategyError("modules are read-only in the sandbox")


SAFE_NP = _SafeModule(np)
SAFE_PD = _SafeModule(pd)


@contextmanager
def time_limit(seconds: float):
    """Raise StrategyTimeout if the block runs longer than `seconds` (Unix only)."""

    def _handler(signum, frame):
        raise StrategyTimeout(f"exceeded {seconds}s")

    old = signal.signal(signal.SIGALRM, _handler)
    signal.setitimer(signal.ITIMER_REAL, seconds)
    try:
        yield
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, old)


def compile_strategy(completion_text: str, timeout: float = 5.0):
    """Extract, exec, and return the `allocate` callable from a completion.

    Raises StrategyError on any contract violation.
    """
    code = extract_code(completion_text)
    if code is None:
        raise StrategyError("no code block / no `def allocate` found")

    namespace = {"__builtins__": SAFE_BUILTINS, "np": SAFE_NP, "pd": SAFE_PD,
                 "math": math}
    try:
        with time_limit(timeout):
            exec(compile(code, "<strategy>", "exec"), namespace)
    except StrategyError:
        raise
    except BaseException as e:  # SyntaxError, ImportError (blocked), etc.
        raise StrategyError(f"exec failed: {type(e).__name__}: {e}") from e

    fn = namespace.get("allocate")
    if not callable(fn):
        raise StrategyError("code defines no callable `allocate`")
    return fn


# --- output validation ----------------------------------------------------------

def clean_weights(raw, universe: list[str]) -> dict[str, float]:
    """Validate an allocate() return value into {ticker: weight}.

    Contract: dict (or Series) of known tickers, long-only, weights in [0,1],
    sum <= 1 (remainder is cash). Small float slop is tolerated; real
    violations raise StrategyError.
    """
    if isinstance(raw, pd.Series):
        raw = raw.to_dict()
    if not isinstance(raw, dict):
        raise StrategyError(f"allocate() returned {type(raw).__name__}, not dict")

    weights: dict[str, float] = {}
    for key, value in raw.items():
        if key == "CASH":
            continue  # cash is implicit; an explicit entry is tolerated
        if key not in universe:
            raise StrategyError(f"unknown ticker {key!r}")
        try:
            v = float(value)
        except (TypeError, ValueError) as e:
            raise StrategyError(f"non-numeric weight for {key}") from e
        if math.isnan(v) or math.isinf(v):
            raise StrategyError(f"non-finite weight for {key}")
        if v < -1e-9:
            raise StrategyError(f"negative weight for {key} (long-only)")
        if v > 1.0 + 1e-6:
            raise StrategyError(f"weight {v:.3f} > 1 for {key}")
        weights[key] = min(max(v, 0.0), 1.0)  # clip float slop only

    total = sum(weights.values())
    if total > 1.0 + 1e-6:
        raise StrategyError(f"weights sum to {total:.3f} > 1")
    return weights
